### ISSUE TITLE
Mug does not warm to target temperature (stuck at default temperature 135F)

### ISSUE THREAD

**Issue by turbo6m** [matthewnitschke/ember-macos#45]
EmberMate appears to connect properly with the mug, and I can set a non-default target temperature (e.g., 143F) via EmberMate.  However, even though the EmberMate shows that the desired target temp is 143, the mug only heats to the default temperature (135F).  The target temp can be set with either the arrow buttons or via a preset (e.g., Coffee).  Neither method works to change the actual temperature of the mug (even though EmberMate shows the desired temperature in the UI).

I've never synced the mug with the official app, only with EmberMate.

![image](https://github.com/user-attachments/assets/fef7e555-bd1a-4a2c-a8ac-1af761daa161)

**Comment by matthewnitschke** [comment]
Interesting, I'd be surprised if this was due to EmberMate, as the application is just reporting the values it gets from the mug

Might be worth connecting it to the official app to verify that the mug itself is working as expected. If it's not, ember support might be able to help you out more than I

**Comment by turbo6m** [comment]
Thanks for the suggestion (and for the amazing EmberMate). Mug and remote temp controls now work as expected. After setting up the official app, I adjusted the target temperature using the official app, which quickly updated the mug’s actual temperature. EmberMate now works seamlessly to also change the actual temperature, though initial setup via the official app may be required, possibly involving account creation or firmware updates for newer mugs.

**Comment by matthewnitschke** [comment]
Nice glad its working for you!
